language: swift
matrix:
    include:
        - osx_image: xcode12.2

before_install:
#   - echo "git \"file://$($(dirname $0); pwd)\"" >> Cartfile
#   - cat Cartfile
    - brew update
    - brew outdated swiftlint || brew upgrade swiftlint
#   - carthage update --platform iOS

script:
    - xcodebuild -scheme FloatingShowable -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=14.2,name=iPhone 12 Pro' -configuration Debug test | xcpretty -c
    - swiftlint

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 61bc1a62-8dfe-4491-a8b1-39025a1d8310

# https://docs.travis-ci.com/user/reference/osx/#xcode-version
# https://docs.travis-ci.com/user/languages/objective-c/

